version: '3.8'

services:
  python-bot:
    build: ./bot
    port: -"8080:8080"
    environment:
      - STORAGE_URL: golang-kvdb:5173
      - TELEGRAM_API_KEY: 7193262302:AAFadZQ58TP9vGRSV4Gl0fj_GB9KAKQrTCU
    depends_on:
      - golang-kvdb
  golang-kvdb:
    build: ./kvdb
    ports:
      - "5173:5173"
    environment:
      DB_FILE: data/db.json
      DB_PORT: 5173
    volumes:
      - kvdb_volume:/app/data

volumes:
  kvdb_volume:
