version: '3.8'

services:
  python-bot:
    build: ./bot
    environment:
      STORAGE_URL: http://golang-kvdb:5173/db/v1
      TELEGRAM_API_KEY: 7193262302:AAFadZQ58TP9vGRSV4Gl0fj_GB9KAKQrTCU
      BACKEND_URL: https://gagarinhack-1.onrender.com/api/v1/
    depends_on:
      - golang-kvdb
  golang-kvdb:
    build: ./kvdb
    ports:
      - "5173:5173"
    environment:
      DB_FILE: data/db.json
      DB_PORT: 5173
    volumes:
      - kvdb_volume:/app/data

volumes:
  kvdb_volume:
