version: '3.8'

services:
  golang-kvdb:
    build: ./kvdb
    ports:
      - "5173:5173"
    environment:
      DB_FILE: data/db.json
      DB_PORT: 5173
    volumes:
      - kvdb_volume:/app/data

volumes:
  kvdb_volume:
